const en = {
  payments: 'Payments',
  payment: 'Payment',
  created: 'Date',
  status: 'Status',
  description: 'Description',
  currency: 'Currency',
  email: 'Email',
  mobile: 'Mobile',
  role: 'Role',
  invoice_number: 'Invoice #',
  customer: 'Customer',
  due: 'Due',
  first_name: 'First name',
  last_name: 'Last name',
  send_emails_to: 'Send emails to',
  billing: 'Billing details',
  invoices: 'Invoices',
  billed_to: 'Billed to',
  amount: 'Amount',
  due_date: 'Due date',
  phone: 'Phone',
  id: 'ID',
  origin: 'Origin',
  payout: 'Payout',
  conversion: 'Conversion',
  invoice: 'Invoice',
  redirect_url: 'Payment page',
  refund: 'Refund',
};

export default en;
